language: nix
cache: ccache
os: linux

before_script:
  - sudo mkdir /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf

jobs:
  include:

    - stage: build
      script: nix-build ./pkgs
      name: "nixpkgs unstable"

    - script: nix-channel --add https://nixos.org/channels/nixos-18.09 nixpkgs && nix-channel --update && nix-build ./pkgs
      name: "nixpkgs 18.09"
