name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - release-20.03
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-20.03
      - uses: cachix/cachix-action@v6
        with:
          name: nixjs
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: |
          nix-build release.nix \
              --argstr nodejs ${{ matrix.nodejs }} \
              --argstr yarn ${{ matrix.yarn }}
    strategy:
      matrix:
        nodejs:
          - 12.16.2
          - 12.16.0
          - 12.14.1
          - 10.19.0
          - 10.15.3
          - 10.15.1
          - 10.15.0
          - 10.14.2
          - 10.14.1
          - 10.13.0
        yarn:
          - 1.22.4
          - 1.22.0
          - 1.21.1
          - 1.16.0
          - 1.12.3
