name: Check

on:
  pull_request:
  push:
    branches:
      - master
      - release-20.03

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out codebase
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-20.03

      - name: Set up cachix
        uses: cachix/cachix-action@v6
        with:
          name: nix-linter
          skipPush: true

      - name: Install packages
        run: nix-build lint.nix

      - name: Run lint
        run: ./result/bin/lint

  format:
    runs-on: ubuntu-latest
    steps:

      - name: Check out codebase
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-20.03

      - name: Install packages
        run: nix-build format.nix

      - name: Check formatting
        run: ./result/bin/format --check
